
modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="endrem" #mandatory

version="1.16.1-1.0.1" #mandatory

displayName="EndRemastered" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.melshin.com/" #optional

logoFile="endremLogo.png" #optional

credits="Thanks to Manchego_Cheese(Textures)
Thanks to Daserta(Russian translation)
Thanks to Marty Lagina(The Idea)" #optional

authors="Shte_Ken" #optional

description='''
A mod that remaster the way you get to the end.
'''
[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[32,)" #mandatory

    ordering="NONE"

    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
